{"uuid": "8f1405fb-1d9c-4eab-a881-588c7b8a3f61", "children": ["abc628cd-d43d-4a27-8457-2690ea9c44c1"], "befores": [{"name": "prepare_to_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"D:\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\pythonProject\\diaoyu_app_auto_test\\cases\\test_login.py\", line 10, in prepare_to_login\n    handler[1].go_to_login_page()\n  File \"E:\\pythonProject\\diaoyu_app_auto_test\\pages\\pages_action.py\", line 47, in go_to_login_page\n    self.click_element(MePageLocator.click_to_login_loc)\n  File \"E:\\pythonProject\\diaoyu_app_auto_test\\common\\bases\\base_page.py\", line 26, in click_element\n    element = self.search_element(locator)\n  File \"E:\\pythonProject\\diaoyu_app_auto_test\\common\\bases\\base_page.py\", line 22, in search_element\n    return self.driver.find_element(*locator)\n  File \"D:\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 276, in find_element\n    'value': value})['value']\n  File \"D:\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python36\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"D:\\Python36\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"D:\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1610783634210, "stop": 1610783645364}], "start": 1610783634210, "stop": 1610783645774}